export default function AboutProject() {

  const features = [
    {
      icon: "🤖",
      title: "AI-Powered Questions",
      desc: "Questions generated by AI tailored to your resume and target role.",
    },

    {
      icon: "👁️",
      title: "Confidence Monitoring",
      desc: "Real-time webcam analysis tracks eye movement and face position during interviews.",
    },

    {
      icon: "💬",
      title: "Adaptive Follow-Ups",
      desc: "The AI asks deeper follow-up questions based on your actual answers.",
    },

    {
      icon: "🧩",
      title: "DSA Practice",
      desc: "Practice coding problems with hints, solutions and in-browser execution.",
    },

    {
      icon: "🎤",
      title: "Voice Support",
      desc: "Answer naturally using Web Speech API voice recognition.",
    },

    {
      icon: "📄",
      title: "Resume Analysis",
      desc: "Upload your resume and get AI-powered ATS suggestions instantly.",
    },
  ];

  return (

    <div className="min-h-screen bg-white text-black px-6 py-20">

      <div className="max-w-6xl mx-auto">

        {/* HEADER */}
        <div className="text-center mb-20">

          <div className="inline-block px-5 py-2 rounded-full border border-blue-200 bg-blue-50 text-blue-600 text-sm mb-6 font-medium">
            ✨ About GetMePlaced
          </div>

          <h1 className="text-5xl md:text-7xl font-extrabold mb-6 leading-tight">

            AI Powered
            <br />

            <span className="bg-gradient-to-r from-blue-500 via-purple-500 to-cyan-500 bg-clip-text text-transparent">
              Interview Platform
            </span>

          </h1>

          <p className="max-w-3xl mx-auto text-gray-600 text-lg leading-8">

            GetMePlaced is an AI-powered interview preparation platform
            designed to help students and professionals practice technical
            interviews, improve problem solving skills, analyze resumes,
            and prepare for real-world hiring processes.

          </p>

        </div>

        {/* FEATURES GRID */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-7">

          {features.map((feature) => (

            <div
              key={feature.title}

              className="group bg-white border border-gray-200 shadow-lg rounded-3xl p-8 transition-all duration-300 hover:-translate-y-2 hover:border-blue-400 hover:shadow-2xl"
            >

              {/* ICON */}
              <div className="text-5xl mb-6">
                {feature.icon}
              </div>

              {/* TITLE */}
              <h3 className="text-2xl font-bold mb-4 text-black">
                {feature.title}
              </h3>

              {/* DESC */}
              <p className="text-gray-600 leading-7 text-sm">
                {feature.desc}
              </p>

              {/* GLOW LINE */}
              <div className="mt-6 h-1 w-16 rounded-full bg-gradient-to-r from-blue-500 to-cyan-400 transition-all duration-300 group-hover:w-28" />

            </div>

          ))}

        </div>

        {/* STATS */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-6 mt-24">

          {[
            ["2400+", "Users"],
            ["150+", "DSA Problems"],
            ["98%", "Success Rate"],
            ["24/7", "AI Support"],
          ].map(([num, label]) => (

            <div
              key={label}

              className="bg-gray-50 border border-gray-200 shadow-md rounded-3xl p-8 text-center transition-all duration-300 hover:shadow-xl"
            >

              <div className="text-4xl font-extrabold bg-gradient-to-r from-blue-500 to-cyan-500 bg-clip-text text-transparent">
                {num}
              </div>

              <div className="text-gray-600 mt-3 text-sm font-medium">
                {label}
              </div>

            </div>

          ))}

        </div>

        {/* FOOTER */}
        <div className="mt-24 text-center">

          <p className="text-gray-500 text-sm">
            Built with AI, React, FastAPI, TailwindCSS and modern web technologies.
          </p>

        </div>

      </div>

    </div>
  );
}